fixit_service:
    resource: "@fixitServiceBundle/Resources/config/routing.yml"
    prefix:   /service

fixit_evaluation:
    resource: "@fixitEvaluationBundle/Resources/config/routing.yml"
    prefix:   /evaluation

fixit_organisation:
    resource: "@fixitOrganisationBundle/Resources/config/routing.yml"
    prefix:   /organisation

fixit_acctualite:
    resource: "@fixitAcctualiteBundle/Resources/config/routing.yml"
    prefix:   /acctualite

fixit_partenariat:
    resource: "@fixitPartenariatBundle/Resources/config/routing.yml"
    prefix:   /partenariat

fixit_annonce:
    resource: "@fixitAnnonceBundle/Resources/config/routing.yml"
    prefix:   /annonce

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications