<?php

namespace fixit\ServiceBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByNom($nom){

        $dqlresult=$this->getEntityManager()->createQuery("SELECT m FROM fixitServiceBundle:Categorie m where m.nom= '$nom'");
        return $dqlresult->getResult();
    }
    public function findByType($type){

        $dqlresult=$this->getEntityManager()->createQuery("SELECT m FROM fixitServiceBundle:Categorie m where m.type= '$type'");
        return $dqlresult->getResult();
    }
}
